version: '3.8'

#docker-compose -f docker-compose-kafka-only.yml up
services:
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "yes"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"  # ✅ для IDEA
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    command:
      - sh
      - -c
      - |
        cat > /tmp/server.properties << EOF
        process.roles=broker,controller
        node.id=1
        controller.quorum.voters=1@localhost:9093
        listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        advertised.listeners=PLAINTEXT://localhost:9092  
        listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        controller.listener.names=CONTROLLER
        inter.broker.listener.name=PLAINTEXT
        log.dirs=/tmp/kraft-combined-logs
        num.partitions=1
        num.recovery.threads.per.data.dir=1
        offsets.topic.replication.factor=1
        transaction.state.log.replication.factor=1
        transaction.state.log.min.isr=1
        EOF
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format -t $$CLUSTER_ID -c /tmp/server.properties --ignore-formatted
        fi
        exec /opt/kafka/bin/kafka-server-start.sh /tmp/server.properties
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 40s
